#!/usr/bin/env bash
# Register a directory of downloaded fonts with fontconfig so rsvg/inkscape actually use them,
# and optionally VERIFY that the faces you intend to use resolve to themselves.
#
# Usage: setup_fonts.sh <fonts-dir> [FAMILY ...]
#
# Prints the FONTCONFIG_FILE=... line to pass INLINE on every render/vectorize command
# (shell state does not persist between tool calls, so `export` won't survive). With families
# named, exits nonzero if any of them resolves to a different face — which is the failure
# nothing downstream can catch, so it is worth stopping for.
#
#   CONF=$(setup_fonts.sh ./collage-fonts Futura Optima | sed 's/FONTCONFIG_FILE=//')
#
# The config itself is generated by fonts.py, which is also what svgkit imports — one
# implementation, so the Python build path and the shell path cannot drift apart. Read that
# module for why the stock macOS config resolves most named faces to Hiragino Sans.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fonts_dir="${1:?usage: setup_fonts.sh <fonts-dir> [FAMILY ...]}"
shift || true

if [ "$#" -gt 0 ]; then
  python3 "$here/fonts.py" --dir "$fonts_dir" --require "$@"
else
  python3 "$here/fonts.py" --dir "$fonts_dir"
fi
